steps:
#Clone from Google Cloud Source Repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone','https://source.developers.google.com/p/endless-gamma-333908/r/github_rev1995_cicd']
    id: 'clone'
logsBucket: 'gs://mylogsbucket'
options:
  logging: GCS_ONLY
  substitution_option: 'ALLOW_LOOSE'
