steps:
#First Clone from Google Cloud Source Repository
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://source.developers.google.com/p/endless-gamma-333908/r/github_rev1995_cicd']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'rc:$BUILD_ID', '-f', 'cicd/UIpageDemo/Dockerfile', '.']
  id: 'build-image-myapp'
  waitFor: ['-']  # The '-' indicates that this step begins immediately.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/endless-gamma-333908/cicd-repo/myapp:$COMMIT_SHA']
  id: 'push-image-to-artifact-registry'
  waitFor: ['build-image-myapp']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'myawesomeapp'
  - '--image'
  - 'us-east1-docker.pkg.dev/endless-gamma-333908/cicd-repo/myapp:$COMMIT_SHA'
  - '--region'
  - 'us-east4'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  waitFor: ['push-image-to-artifact-registry']
  id: 'deploy-to-cloud-run'
options:
  #logging: NONE
  substitution_option: 'ALLOW_LOOSE'
